# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amanda's Notes
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amandaeng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  amandaeng
repository: "amandaeng/amandaeng.github.io"
# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
# Site Author
author:
  name: "Amanda"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Wubba lubba dub dub"
  location: "Seattle, WA"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://amandaeng.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/setttings"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "adf"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com"
